# Generated by Django 4.0.8 on 2023-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20200128_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregistration',
            name='department',
            field=models.CharField(choices=[('general', 'Class 10'), ('science', 'Science'), ('business', 'Business'), ('humanities', 'Humanities')], max_length=15),
        ),
    ]
